POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test1",
    "number": "01"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "02"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test3",
    "number": ""
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test1",
    "number": "04595674"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "just tiina",
    "number": "04"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "kuu ukkeli",
    "number": "07890"
}